# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lilian de Greef
author: Lilian de Greef
email: ldegreef@uw.edu
description: Home page for Lilian de Greef, computer science PhD student at the University of Washington.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: www.ldegreef.com
#url: "https://ldegreef.github.io" # the base hostname & protocol for your site
#github_username:  ldegreef
linkedin_username: liliandegreef

# Collections
collections:
  projects:
    output: true
  press:
    output: true
    
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown

exclude: 
    - bower_components/bootstrap/CHANGELOG.md
    - bower_components/bootstrap/README.md
    - bower_components/jquery/README.md